FROM nchannelqa/base-nodejs-image:1.0.6
MAINTAINER nchanneldeveloper <developers@nchannel.com>

# Create app directory
RUN mkdir -p /sdk
WORKDIR /sdk

# Create VOLUME for source
COPY package.json /sdk

COPY . /sdk

RUN chown -R node:node /sdk

RUN chmod +x ./hooks/*
RUN chmod +x ./runTest.sh

RUN npm install

USER root

CMD [ "./runTest.sh" ]
